name: Deploy Frontend to Render

on:
  push:
    paths:
      - 'src/**'
      - 'public/**'
      - 'vite.config.ts'
      - 'render.yaml'
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}